version: '3.7'

services:

  cra:
    image: react:app
    # mounting the source directory with the following env allows warm reloading
    volumes:
      - '.:/learning-github-actions'
      - '/learning-github-actions/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
