# caller action that will orchestrate building, testing, and pushing a PR's image
name: PR QA

on:
  push:

jobs:
  build-and-push-slug:
    name: Build Slug And Push for Testing
    uses: './.github/workflows/build-and-push-image.yml'
    with:
      DOCKER_REPO: 'jamesvobui/learning-github-actions'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  run-unit-tests:
    name: Run Cypress Test
    needs: build-and-push-slug
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v3

      - name: Authorize Docker
        uses: docker/login-action@v1
        with:
          username: jamesvobui
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Cypress Tests
        run: 'docker-compose up --exit-code-from test'
        env:
          # env variable that will either allow cypress to group runners together and optimize them or just a label
          GROUP_NAME: ${{ matrix.containers }}
          # tag of the application that will be spun up and exposed for cypress
          TAG: ${{ needs.build-and-push-slug.outputs.image-tag}}
