name: Require Pull Request for Pushing to Main

on:
  pull_request:
    branches:
      - main

jobs:
  job:
    name: require-pull-request-on-main
    runs-on: ubuntu-latest
      steps:
        - run: echo hello
