name: QA after build-and-push-image

# testing that the workflow run will automatically trigger off of a build workflow's completion
on:
  workflow_run:
    workflows: [ Slug Build & Push to Dockerhub ]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
