name: QA after build-and-push-image

# testing that the workflow run will automatically trigger off of a build workflow's completion
on:
  workflow_run:
    workflows: [test, Pull Request Quality Check]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow named ${{ github.event.workflow.name }} passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow name ${{ github.event.workflow.name }} failed'
